{{- if .Values.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: ai-evaluation-secrets
  labels:
    {{- include "be-ai-evaluation-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.data }}
  {{- range $key, $value := .Values.secrets.data }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}